# Generated by Django 5.1.6 on 2025-02-14 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 14, 8, 19, 11, 96525, tzinfo=datetime.timezone.utc)),
        ),
    ]
